spring.application.name=collageCounselling
spring.mongodb.uri=${MONGO_DB_URL}
spring.data.mongodb.auto-index-creation=true
#jwt.secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
jwt.secret=VGhpc0lzQVNlY3VyZVJhbmRvbUpXVFNlY3JldEtleUZvckhTMjU2QWxnb3JpdGhtMTIzNDU2Nzg5
jwt.expiry=900
