spring.application.name=collageCounselling
spring.mongodb.uri=mongodb+srv://hariommahajan22_db_user:Ox99RPOcR8Q2Y6Yo@cluster0.d4jkp7j.mongodb.net/collageCounselling?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true
